#' Fit permanova models and arrange by AICc
#'
#' @param all_forms A data frame generated by \code{\link{make_models}}
#' @param veg_data A dataset with vegetation presence absense or abundance data
#' @param env_data A dataset with the variables described in all_froms
#' @param ncores An integer specifying the number of cores to use for parallel processing
#' @param log logical if true, a log file will be generated
#' @param logfile the text file that will be generated as a log
#' @param multiple after how many loops to write a log file
#' @param method method for distance from \code{\link{vegdist}}
#' @importFrom parallel makeCluster stopCluster
#' @importFrom doParallel registerDoParallel
#' @importFrom foreach foreach
#' @importFrom vegan vegdist adonis2
#' @importFrom dplyr bind_rows bind_cols select filter arrange
#' @importFrom broom tidy
#' @importFrom tidyr pivot_longer
#' @importFrom stringr str_replace_all
#' @importFrom stats rnorm lm as.formula
#' @examples
#'
#' library(vegan)
#' data(dune)
#' data(dune.env)
#'
#' AllModels <- make_models(vars = c("A1", "Moisture", "Manure"))
#'
#' fit_models(all_forms = AllModels,
#'            veg_data = dune,
#'            env_data = dune.env)
#' @export

fit_models <- function(all_forms,
                       veg_data,
                       env_data,
                       method = "bray",
                       ncores = 2,
                       log = T,
                       logfile = "log.txt",
                       multiple = 100){
  AICc <- R2 <- term <- x <- NULL
  if(log){
    if(file.exists(logfile)){
      file.remove(logfile)
    }
  }

  meta_data <- all_forms
  vegetation_data = veg_data

  cl <- parallel::makeCluster(ncores)
  doParallel::registerDoParallel(cl)

  Distance <- vegan::vegdist(vegetation_data, method = method)

  Fs <- foreach(x = 1:nrow(meta_data), .packages = c("vegan", "dplyr", "AICcPerm", "tidyr", "broom"), .combine = bind_rows, .export = "Distance") %dopar% {

      Response = env_data
      Response$y <- rnorm(n = nrow(Response))
      gc()

      Temp <- meta_data[x,]

      Model <- try(vegan::adonis2(as.formula(Temp$form[1]), data = Response, by = "margin"))

      Temp$AICc <-  try(AICcPerm::AICc_permanova2(Model)$AICc, silent = T)
      Temp$max_vif <- VIF(lm(as.formula(stringr::str_replace_all(Temp$form[1], "Distance ", "y")), data = Response))

      Rs <- broom::tidy(Model) |>
        dplyr::filter(!(term %in% c("Residual", "Total"))) |>
        dplyr::select(term, R2) |>
        tidyr::pivot_wider(names_from = term, values_from = R2)
      if(log){
        if((x %% multiple) == 0){
          sink(logfile, append = T)
          cat(paste("finished", x, "number of models", Sys.time(), "of",  nrow(meta_data)))
          cat("\n")
          sink()
        }

      }

      Temp <- bind_cols(Temp, Rs)
      Temp
    }
  parallel::stopCluster(cl)
  Fs <- Fs |>
    dplyr::arrange(AICc)
  return(Fs)
}

#' Get maximum VIF from a model
#'
#' @param model a model to fit into vif
#' @importFrom car vif

VIF <- function(model) {
      tryCatch({
         vif <- car::vif(model)
         max(vif)
       }, error = function(e) {
         if (grepl("aliased coefficients", e$message)) {
           20000
         } else if (grepl("model contains fewer than 2 terms", e$message)) {
           0
         } else {
           stop(e)
         }
       })
     }
